### ISSUE TITLE
Property 'method' does not exist on type 'Element | Element[] | Vue | Vue[]'

### ISSUE THREAD

**Issue by SumNeuron** [justrhysism/vue-mixin-decorator#47]
I have a component which extends a mixin

```ts
// ...
@Component
export default class MyComp extends Mixins<MyMixin>(MyMixin) {
  // ...
  public myMethod(): void {
    console.log('hello')
  }
}
```

I have another component which uses this component, assigns a `ref` to it, and in a method tries to call `myMethod`, e.g. 

```ts

@Component({components: {MyComp} })
export default class AnotherComp extends Mixins<ADifferentMixin>(ADifferentMixin) {
  private refMethod() {
    this.$refs.myCompRef.myMethod()
  } 
}

```

and I get the error

```
Property 'MyMethod' does not exist on type 'Element | Element[] | Vue | Vue[]'.

```

what am I doing wrong?

**Comment by justrhysism** [comment]
@SumNeuron Vue `$refs` could be [many different types](https://github.com/vuejs/vue/blob/dev/types/vue.d.ts#L29), [not just Vue components](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements). TS can't know what type a specific `ref` is; nor is this the problem which this module is trying to solve.

You will need to use typescript [type assertions](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) to inform the compiler what the type is.

e.g.

```ts
@Component({components: {MyComp} })
export default class AnotherComp extends Mixins<ADifferentMixin>(ADifferentMixin) {
  private refMethod() {
    (<MyComp> this.$refs.myCompRef).myMethod()
  } 
}
```

Or via assignment:

```ts
@Component({components: {MyComp} })
export default class AnotherComp extends Mixins<ADifferentMixin>(ADifferentMixin) {
  private refMethod() {
    const myComp: MyComp = this.$refs.myCompRef
    myComp.myMethod()
  } 
}
```
