### ISSUE TITLE
Support ECMAScript users

### ISSUE THREAD

**Issue by joma74** [justrhysism/vue-mixin-decorator#9]
Would be great if supported for ECMAScript. As in https://github.com/vuejs/vue-class-component via ECMAScript stage 1 decorators.

My use case is mostly for code completion so that
```js
// HomePage.vue/script
@Component({
  name: "HomePage",
  mixins: [routeMixin]
})
export default class HomePage extends Vue {
   assignData(data) {
      this.abc(); <- is intellisensed
   }
...
```
```js
// route-mixin.js
/**
 * @type {ComponentOptions}
 */
let routerMixin = { // might also be written as class extends Vue
  abc: () => {
  }
};
export default routerMixin;
```

**Comment by justrhysism** [comment]
I'm not sure this is possible, but I will take a look into it.

For anyone reading, tips or even PRs are welcome :)

**Comment by joma74** [comment]
Thanks, seems now supported in https://github.com/vuejs/vue-class-component#using-mixins

**Comment by justrhysism** [comment]
I saw that and was just about to close this issue referencing the PR 😄 

I haven't played with the "official" implementation yet, if it provides Typescript typings, then I can deprecate this project 🎉

**Comment by joma74** [comment]
Certainly vue-class-component delivers ES compatibilty. That brings in a certain JS twist to the solution, as you can see in the updated README over there. 

Tried it instantly i noticed the new version. I am on the JS side of things, sprinkeling TS JSDoc and a few d.ts as i see fit.

Anyways, thank you for having welcomeing me.
